-- DADOS PARA LOGIN DO CANDIDATO
SELECT
    I.CD_PSE,
    TRIM(I.NU_CPF),
    TO_CHAR(I.DT_NASC, 'DD/MM/YYYY')
FROM PSE.TB_INSCRICAO I
         INNER JOIN PSE.TB_PSE_CRM CRM
                    ON CRM.CD_PSE = I.CD_PSE
WHERE
    CRM.ID_PSE_CRM = 108
  AND I.NU_CPF = '063.135.197-36';